import yurr from '../assets/yurr.png'

export default function DashboardPage() {

    return (
        <div className="text-center text-pink-400">
            <img src={yurr} className="pt-25 w-[500px] h-[500px] mx-125"></img>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
        </div>
    );
}