export default function DashboardPage() {

    return (
        <div className="text-center text-pink-400">
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
            <p>ts pmo icl rs sybau</p>
        </div>
    );
}