export default function DashboardPage() {

    return (
        <div className="text-center">
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
            <p>hi</p>
        </div>
    );
}